### ISSUE TITLE
Feat: User Management 기능 구현 및 테스트

### ISSUE THREAD

**Issue by LLSNsssz** [LLSNsssz/MachuTogether#10]
## TODO
  - [x] User 엔티티 구현
  - [x] UserRegistrationDto 구현
  - [x] UserMapper 인터페이스 및 구현체 생성
  - [x] UserRepository 인터페이스 생성
  - [x] UserService 인터페이스 및 구현체 생성
  - [x] UserController 구현
  - [x] 단위 테스트 작성
    - [x] UserTest (엔티티 테스트)
    - [x] UserRegistrationDtoTest (DTO 테스트)
    - [x] UserMapperTest (매퍼 테스트)
    - [x] UserRepositoryTest (리포지토리 테스트)
    - [x] UserServiceTest (서비스 테스트)
    - [x] UserControllerTest (컨트롤러 테스트)
  - [x] 통합 테스트 작성

## 설명
User 관리를 위한 전체 구조를 구현하고 각 컴포넌트에 대한 세분화된 단위 테스트를 작성합니다. 
엔티티, DTO, 리포지토리, 서비스, 컨트롤러를 포함한 전체 레이어를 구현하며, 각 컴포넌트에 
적절한 유효성 검사와 비즈니스 로직을 추가합니다. 비밀번호 암호화, 이메일/전화번호 유일성, 
적절한 예외 처리 등을 고려하고, RESTful API 설계 원칙을 준수하여 컨트롤러를 구현합니다. 
각 컴포넌트별 단위 테스트를 통해 개별 기능의 정확성을 검증하고, 최종적으로 통합 테스트를 
통해 전체 기능의 정합성을 확인합니다.
